-- Auto-generated from src/data/products.js — run after schema.sql

insert into public.categories (slug, name, blurb, sort_order) values
  ($sql$foil-balloons$sql$, $sql$Foil Balloons$sql$, $sql$Heart, round, star, numbers & letters in 12 premium colours.$sql$, 0),
  ($sql$bubble-balloons$sql$, $sql$Bubble & Specialty$sql$, $sql$Crystal-clear stretchy bubbles built for long float time.$sql$, 1),
  ($sql$accessories$sql$, $sql$Inflation & Accessories$sql$, $sql$Pumps, weights, ribbons, clips — everything to build the set-up.$sql$, 2)
on conflict (slug) do update set name = excluded.name, blurb = excluded.blurb, sort_order = excluded.sort_order;

insert into public.products
  (slug, name, sku, category_id, shape, theme, price, compare_at, colors, sizes, specs, short, description, visual, badge, is_featured, rating, reviews_count)
values
  ($sql$heart-foil-balloon$sql$, $sql$Heart Foil Balloon$sql$, $sql$FG18025–FG18036$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$heart$sql$, $sql$wedding$sql$, 4.5, 6, $json$["Gold","Silver","Rose Gold","Blue","Rose","Baby Blue","Baby Pink","Black","White","Red","Green","Purple"]$json$::jsonb, $json$[{"label":"10\"","price":2.5},{"label":"18\"","price":4.5},{"label":"24\"","price":7.5}]$json$::jsonb, $json$[{"label":"Inflated size","value":"18 inch / 45 cm (standard)"},{"label":"Helium support","value":"Yes — self-sealing valve"},{"label":"Float time","value":"5–7 days with helium"},{"label":"Material","value":"Premium nylon foil, reusable"}]$json$::jsonb, $sql$Classic heart shape in 12 colours, 5"/10"/18"/24".$sql$, $sql$Our best-selling heart foil balloon — a wedding, anniversary and Valentine's staple. Self-sealing valve holds helium for 5–7 days and the nylon foil can be deflated and reused for the next set-up.$sql$, $json${"kind":"heart","color":"#e8bcae"}$json$::jsonb, $sql$Bestseller$sql$, true, 4.9, 214),
  ($sql$round-foil-balloon$sql$, $sql$Round Foil Balloon$sql$, $sql$FG18013–FG18024$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$round$sql$, $sql$birthday$sql$, 4.5, NULL, $json$["Gold","Silver","Rose Gold","Blue","Rose","Baby Blue","Baby Pink","Black","White","Red","Green","Purple"]$json$::jsonb, $json$[{"label":"10\"","price":2.5},{"label":"18\"","price":4.5},{"label":"24\"","price":7.5}]$json$::jsonb, $json$[{"label":"Inflated size","value":"18 inch / 45 cm (standard)"},{"label":"Helium support","value":"Yes — self-sealing valve"},{"label":"Float time","value":"5–7 days with helium"},{"label":"Material","value":"Premium nylon foil, reusable"}]$json$::jsonb, $sql$Clean round profile — the workhorse of any balloon wall.$sql$, $sql$The round foil balloon is the base of every professional cluster and balloon wall. Uniform metallic finish across all 12 colours so your set-ups stay perfectly matched.$sql$, $json${"kind":"round","color":"#d9b352"}$json$::jsonb, NULL, true, 4.8, 168),
  ($sql$star-foil-balloon$sql$, $sql$Star Foil Balloon$sql$, $sql$FG18001–FG18012$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$star$sql$, $sql$birthday$sql$, 4.5, NULL, $json$["Gold","Silver","Rose Gold","Blue","Rose","Baby Blue","Baby Pink","Black","White","Red","Green","Purple"]$json$::jsonb, $json$[{"label":"10\"","price":2.5},{"label":"18\"","price":4.5},{"label":"24\"","price":7.5}]$json$::jsonb, $json$[{"label":"Inflated size","value":"18 inch / 45 cm (standard)"},{"label":"Helium support","value":"Yes — self-sealing valve"},{"label":"Float time","value":"5–7 days with helium"},{"label":"Material","value":"Premium nylon foil, reusable"}]$json$::jsonb, $sql$Five-point star, mirror-metallic finish.$sql$, $sql$Sharp five-point stars that photograph beautifully under event lighting. Mix gold and silver for graduation and New Year set-ups.$sql$, $json${"kind":"star","color":"#3382f0"}$json$::jsonb, NULL, true, 4.8, 132),
  ($sql$number-foil-balloon-32$sql$, $sql$32" Number Foil Balloon (0–9)$sql$, $sql$FE-NUM32$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$number-letter$sql$, $sql$birthday$sql$, 12, 16, $json$["Gold","Silver","Rose Gold","Blue","Baby Pink","Black"]$json$::jsonb, $json$[{"label":"16\"","price":7},{"label":"32\"","price":12},{"label":"40\"","price":19}]$json$::jsonb, $json$[{"label":"Inflated size","value":"32 inch / 81 cm"},{"label":"Digits","value":"0 – 9 available"},{"label":"Fill","value":"Air or helium"},{"label":"Float time","value":"3–5 days with helium"}]$json$::jsonb, $sql$Jumbo age numbers for birthday backdrops.$sql$, $sql$Jumbo 32 inch number balloons — the centrepiece of every birthday backdrop. Air-fill for wall mounting or helium-fill to float.$sql$, $json${"kind":"number","color":"#d9b352","label":"5"}$json$::jsonb, $sql$Top rated$sql$, true, 4.9, 301),
  ($sql$letter-foil-balloon-16$sql$, $sql$16" Letter Foil Balloon (A–Z)$sql$, $sql$FE-LTR16$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$number-letter$sql$, $sql$wedding$sql$, 9, NULL, $json$["Gold","Silver","Rose Gold","Baby Pink"]$json$::jsonb, $json$[{"label":"16\"","price":9},{"label":"32\"","price":14}]$json$::jsonb, $json$[{"label":"Inflated size","value":"16 inch / 40 cm"},{"label":"Letters","value":"A – Z available"},{"label":"Fill","value":"Air recommended"}]$json$::jsonb, $sql$Spell out any name, A to Z.$sql$, $sql$Build custom names and phrases — MR & MRS, BRIDE, HAPPY EID. Each letter ships with a self-sealing valve and hanging tab.$sql$, $json${"kind":"number","color":"#e8bcae","label":"A"}$json$::jsonb, NULL, false, 4.7, 88),
  ($sql$4d-sphere-mirror-balloon$sql$, $sql$4D Sphere Mirror Balloon$sql$, $sql$FE-4D$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$round$sql$, $sql$wedding$sql$, 6, NULL, $json$["Silver","Gold","Rose Gold","Blue","Rose"]$json$::jsonb, $json$[{"label":"10\"","price":6},{"label":"18\"","price":12},{"label":"22\"","price":18},{"label":"32\"","price":32},{"label":"50\"","price":68}]$json$::jsonb, $json$[{"label":"Sizes","value":"10\" · 12\" · 15\" · 18\" · 22\" · 32\" · 50\""},{"label":"Finish","value":"High-gloss mirror chrome"},{"label":"Fill","value":"Air or helium"}]$json$::jsonb, $sql$Mirror-finish spheres from 10 inch up to 50 inch.$sql$, $sql$Perfectly spherical 4D mirror balloons — the high-impact statement piece. Available from 10 inch right up to a 50 inch showstopper for entrances and stage set-ups.$sql$, $json${"kind":"sphere","color":"#c7ccd2"}$json$::jsonb, $sql$New$sql$, true, 4.9, 156),
  ($sql$happy-birthday-balloon-set$sql$, $sql$Happy Birthday Balloon Set$sql$, $sql$FE-SET-BD$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$round$sql$, $sql$birthday$sql$, 35, 48, $json$["Rose Gold","Gold","Blue"]$json$::jsonb, $json$[{"label":"Set of 16","price":35}]$json$::jsonb, $json$[{"label":"Includes","value":"16 balloons + ribbon + glue dots"},{"label":"Coverage","value":"One 1.5m backdrop cluster"}]$json$::jsonb, $sql$Ready-to-hang birthday cluster, 16 pieces.$sql$, $sql$A complete birthday cluster in one box: banner balloons, confetti rounds, hearts and stars, plus ribbon and glue dots. Built for decorators who need a fast, repeatable set-up.$sql$, $json${"kind":"cluster","color":"#e8bcae"}$json$::jsonb, NULL, false, 4.8, 97),
  ($sql$bride-to-be-set$sql$, $sql$Bride To Be Balloon Set$sql$, $sql$FE-SET-WD$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$number-letter$sql$, $sql$wedding$sql$, 42, NULL, $json$["Rose Gold","White","Gold"]$json$::jsonb, $json$[{"label":"Set of 20","price":42}]$json$::jsonb, $json$[{"label":"Includes","value":"20 balloons + ribbon"},{"label":"Theme","value":"Bridal / engagement"}]$json$::jsonb, $sql$Engagement and bridal shower kit.$sql$, $sql$Rose gold lettering, pearl-white rounds and heart accents — the complete bridal shower and engagement kit.$sql$, $json${"kind":"cluster","color":"#f3b9cd"}$json$::jsonb, NULL, false, 4.9, 64),
  ($sql$jungle-safari-balloon-set$sql$, $sql$Jungle Safari Animal Set$sql$, $sql$FE-SET-AN$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$round$sql$, $sql$animal$sql$, 28, NULL, $json$["Green","Gold"]$json$::jsonb, $json$[{"label":"Set of 14","price":28}]$json$::jsonb, $json$[{"label":"Includes","value":"14 balloons"},{"label":"Theme","value":"Jungle / safari"}]$json$::jsonb, $sql$Animal-print and jungle-theme kids kit.$sql$, $sql$Lion, giraffe and zebra character foils with palm-leaf accents — the go-to kit for kids' jungle parties.$sql$, $json${"kind":"cluster","color":"#128740"}$json$::jsonb, NULL, false, 4.7, 51),
  ($sql$seasonal-halloween-set$sql$, $sql$Halloween Balloon Set$sql$, $sql$FE-SET-HW$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$round$sql$, $sql$seasonal$sql$, 30, NULL, $json$["Black","Purple"]$json$::jsonb, $json$[{"label":"Set of 12","price":30}]$json$::jsonb, $json$[{"label":"Includes","value":"12 balloons"},{"label":"Theme","value":"Halloween"}]$json$::jsonb, $sql$Pumpkins, bats and spider webs.$sql$, $sql$Seasonal Halloween cluster — pumpkin rounds, bat cut-outs and black-purple foil mix.$sql$, $json${"kind":"cluster","color":"#6d28c9"}$json$::jsonb, NULL, false, 4.6, 39),
  ($sql$confetti-print-round$sql$, $sql$Confetti Print Round Balloon$sql$, $sql$FE-CFT18$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$round$sql$, $sql$birthday$sql$, 6, NULL, $json$["Rose Gold","Gold","Silver"]$json$::jsonb, $json$[{"label":"18\"","price":6},{"label":"24\"","price":9}]$json$::jsonb, $json$[{"label":"Inflated size","value":"18 inch / 45 cm (standard)"},{"label":"Helium support","value":"Yes — self-sealing valve"},{"label":"Float time","value":"5–7 days with helium"},{"label":"Material","value":"Premium nylon foil, reusable"}]$json$::jsonb, $sql$Metallic confetti print on clear foil.$sql$, $sql$Printed confetti detail that reads as real confetti on camera, without the clean-up.$sql$, $json${"kind":"round","color":"#f3b9cd"}$json$::jsonb, NULL, false, 4.7, 72),
  ($sql$baby-shower-set$sql$, $sql$Baby Shower Balloon Set$sql$, $sql$FE-SET-BS$sql$, (select id from public.categories where slug = $sql$foil-balloons$sql$), $sql$round$sql$, $sql$birthday$sql$, 32, NULL, $json$["Baby Blue","Baby Pink","White"]$json$::jsonb, $json$[{"label":"Set of 15","price":32}]$json$::jsonb, $json$[{"label":"Includes","value":"15 balloons + ribbon"},{"label":"Theme","value":"Baby shower"}]$json$::jsonb, $sql$Oh Baby! cluster in pastel tones.$sql$, $sql$Pastel blue and pink cluster with OH BABY lettering — gender reveal and baby shower ready.$sql$, $json${"kind":"cluster","color":"#8fc6ee"}$json$::jsonb, NULL, false, 4.8, 83),
  ($sql$crystal-clear-bubble-balloon$sql$, $sql$Crystal Clear Bubble Balloon$sql$, $sql$FE-BUB18$sql$, (select id from public.categories where slug = $sql$bubble-balloons$sql$), NULL, NULL, 12, 16, $json$["Clear"]$json$::jsonb, $json$[{"label":"18\"","price":12},{"label":"24\"","price":18},{"label":"36\"","price":34}]$json$::jsonb, $json$[{"label":"Material","value":"Stretchy TPU — tear resistant"},{"label":"Helium","value":"Compatible — floats beautifully"},{"label":"Preparation","value":"Pre-stretch gently in all directions"},{"label":"Reusable","value":"Yes, deflate and refill"}]$json$::jsonb, $sql$Stretchy TPU bubble — pre-stretch before filling.$sql$, $sql$Durable, crystal-clear stretchy bubble balloons made from TPU. Tear-resistant, reusable and stunning when filled with smaller balloons, feathers or LED strings. Always pre-stretch in every direction before inflating.$sql$, $json${"kind":"bubble","color":"#bcdcff"}$json$::jsonb, $sql$Bestseller$sql$, true, 4.9, 187),
  ($sql$printed-bubble-balloon$sql$, $sql$Printed Happy Birthday Bubble$sql$, $sql$FE-BUBP22$sql$, (select id from public.categories where slug = $sql$bubble-balloons$sql$), NULL, NULL, 22, NULL, $json$["Clear"]$json$::jsonb, $json$[{"label":"22\"","price":22}]$json$::jsonb, $json$[{"label":"Inflated size","value":"22 inch / 56 cm"},{"label":"Print","value":"Gold script, both sides"},{"label":"Helium","value":"Compatible"}]$json$::jsonb, $sql$Script print on a crystal bubble.$sql$, $sql$Gold script 'Happy Birthday' printed on a 22 inch crystal bubble — a finished gift on its own.$sql$, $json${"kind":"bubble","color":"#ffe9d4"}$json$::jsonb, NULL, false, 4.8, 74),
  ($sql$feather-filled-bubble$sql$, $sql$Feather Filled Bubble Balloon$sql$, $sql$FE-BUBF20$sql$, (select id from public.categories where slug = $sql$bubble-balloons$sql$), NULL, NULL, 26, NULL, $json$["Clear","Rose Gold","White"]$json$::jsonb, $json$[{"label":"20\"","price":26}]$json$::jsonb, $json$[{"label":"Inflated size","value":"20 inch / 50 cm"},{"label":"Fill","value":"Feathers included"},{"label":"Helium","value":"Recommended"}]$json$::jsonb, $sql$Pre-filled with soft feathers.$sql$, $sql$Bubble balloon pre-filled with soft feathers — floats with a slow, luxurious drift.$sql$, $json${"kind":"bubble","color":"#f3b9cd"}$json$::jsonb, NULL, false, 4.7, 42),
  ($sql$bobo-balloon-pack$sql$, $sql$Bobo Balloon Pack (10 pcs)$sql$, $sql$FE-BOBO10$sql$, (select id from public.categories where slug = $sql$bubble-balloons$sql$), NULL, NULL, 55, NULL, $json$["Clear"]$json$::jsonb, $json$[{"label":"10 pack","price":55},{"label":"50 pack","price":240}]$json$::jsonb, $json$[{"label":"Pack size","value":"10 or 50 pieces"},{"label":"Size","value":"18 inch"},{"label":"Material","value":"Stretchy TPU"}]$json$::jsonb, $sql$Wholesale bobo packs for decorators.$sql$, $sql$Wholesale bobo balloon packs for decorators running multiple events a week. Bulk pricing available.$sql$, $json${"kind":"bubble","color":"#d9ecff"}$json$::jsonb, NULL, false, 4.8, 35),
  ($sql$electric-balloon-pump$sql$, $sql$Electric Balloon Pump$sql$, $sql$FE-PUMP-E$sql$, (select id from public.categories where slug = $sql$accessories$sql$), NULL, NULL, 249, 320, $json$["Pink","Blue"]$json$::jsonb, $json$[{"label":"Dual nozzle","price":249}]$json$::jsonb, $json$[{"label":"Voltage","value":"220V – 240V"},{"label":"Power","value":"600W"},{"label":"Nozzles","value":"2 (dual)"},{"label":"Airflow","value":"Continuous"}]$json$::jsonb, $sql$600W, dual nozzle, continuous airflow.$sql$, $sql$Professional dual-nozzle electric pump with continuous airflow — inflate a full balloon garland in minutes instead of hours. Built for daily commercial use.$sql$, $json${"kind":"pump","color":"#e0308f"}$json$::jsonb, $sql$Pro pick$sql$, true, 4.9, 128),
  ($sql$hand-balloon-pump$sql$, $sql$Hand Balloon Pump$sql$, $sql$FE-PUMP-H$sql$, (select id from public.categories where slug = $sql$accessories$sql$), NULL, NULL, 25, NULL, $json$["Green","Blue","Red"]$json$::jsonb, $json$[{"label":"Dual action","price":25}]$json$::jsonb, $json$[{"label":"Type","value":"Dual action"},{"label":"Weight","value":"180 g"},{"label":"Use","value":"Foil & latex balloons"}]$json$::jsonb, $sql$Lightweight, portable, dual action.$sql$, $sql$Dual-action hand pump — inflates on both push and pull. Light enough to keep in the event kit.$sql$, $json${"kind":"pump","color":"#128740"}$json$::jsonb, NULL, false, 4.6, 61),
  ($sql$balloon-weight$sql$, $sql$Foil Balloon Weight (170g)$sql$, $sql$FE-WT170$sql$, (select id from public.categories where slug = $sql$accessories$sql$), NULL, NULL, 12, NULL, $json$["Rose","Gold","Silver","Blue","Black"]$json$::jsonb, $json$[{"label":"170 g","price":12},{"label":"Pack of 10","price":100}]$json$::jsonb, $json$[{"label":"Weight","value":"170 g (approx.)"},{"label":"Holds","value":"Up to 50 balloons"},{"label":"Colours","value":"5 metallic finishes"}]$json$::jsonb, $sql$Holds up to 50 balloons. Multiple colours.$sql$, $sql$Tasselled foil weight that anchors clusters and centrepieces without tipping.$sql$, $json${"kind":"weight","color":"#e0308f"}$json$::jsonb, NULL, true, 4.7, 54),
  ($sql$curling-ribbon-spool$sql$, $sql$Curling Ribbon Spool$sql$, $sql$FE-RIB250$sql$, (select id from public.categories where slug = $sql$accessories$sql$), NULL, NULL, 9, NULL, $json$["Purple","Gold","Silver","Red","Baby Blue","White"]$json$::jsonb, $json$[{"label":"250 yards","price":9},{"label":"Pack of 6","price":48}]$json$::jsonb, $json$[{"label":"Length","value":"250 yards"},{"label":"Width","value":"5 mm"},{"label":"Colours","value":"Multiple"}]$json$::jsonb, $sql$250 yards per spool, premium quality.$sql$, $sql$High-shine curling ribbon that holds a curl in UAE heat and humidity.$sql$, $json${"kind":"ribbon","color":"#6d28c9"}$json$::jsonb, NULL, true, 4.6, 47),
  ($sql$balloon-sealing-clips$sql$, $sql$Balloon Sealing Clips (100 pcs)$sql$, $sql$FE-CLIP100$sql$, (select id from public.categories where slug = $sql$accessories$sql$), NULL, NULL, 7, NULL, $json$["Blue","White"]$json$::jsonb, $json$[{"label":"Pack of 100","price":7},{"label":"Pack of 500","price":30}]$json$::jsonb, $json$[{"label":"Pack","value":"100 pieces"},{"label":"Use","value":"Latex balloons"},{"label":"Reusable","value":"Yes"}]$json$::jsonb, $sql$Secure seal, easy to use, pack of 100.$sql$, $sql$Fast-seal clips for latex balloons — no knot tying, no sore fingers on a 200-balloon garland.$sql$, $json${"kind":"clip","color":"#1f7fe0"}$json$::jsonb, NULL, true, 4.5, 66),
  ($sql$balloon-glue-dots$sql$, $sql$Balloon Glue Dots (500 pcs)$sql$, $sql$FE-GLUE500$sql$, (select id from public.categories where slug = $sql$accessories$sql$), NULL, NULL, 15, NULL, $json$["Clear"]$json$::jsonb, $json$[{"label":"500 dots","price":15}]$json$::jsonb, $json$[{"label":"Quantity","value":"500 dots"},{"label":"Residue","value":"Removable, low residue"}]$json$::jsonb, $sql$Removable adhesive dots for garlands.$sql$, $sql$Double-sided removable dots that hold balloons in place on walls, arches and backdrops.$sql$, $json${"kind":"clip","color":"#3382f0"}$json$::jsonb, NULL, false, 4.7, 43),
  ($sql$balloon-arch-strip$sql$, $sql$Balloon Arch Decorating Strip (5m)$sql$, $sql$FE-ARCH5$sql$, (select id from public.categories where slug = $sql$accessories$sql$), NULL, NULL, 12, NULL, $json$["Clear"]$json$::jsonb, $json$[{"label":"5 m","price":12},{"label":"10 m","price":20}]$json$::jsonb, $json$[{"label":"Length","value":"5 m or 10 m"},{"label":"Holes","value":"Pre-punched, dual row"}]$json$::jsonb, $sql$Punched strip for fast garland building.$sql$, $sql$Pre-punched decorating strip — the fastest way to build a professional balloon garland.$sql$, $json${"kind":"ribbon","color":"#59a5fb"}$json$::jsonb, NULL, false, 4.8, 58),
  ($sql$balloon-tying-tool$sql$, $sql$Balloon Tying Tool$sql$, $sql$FE-TIE$sql$, (select id from public.categories where slug = $sql$accessories$sql$), NULL, NULL, 6, NULL, $json$["Pink","Blue"]$json$::jsonb, $json$[{"label":"Single","price":6}]$json$::jsonb, $json$[{"label":"Material","value":"ABS plastic"},{"label":"Use","value":"Latex balloons"}]$json$::jsonb, $sql$Saves your fingers on big set-ups.$sql$, $sql$Ergonomic tying tool for high-volume knot work.$sql$, $json${"kind":"clip","color":"#e0308f"}$json$::jsonb, NULL, false, 4.5, 29),
  ($sql$balloon-garland-kit$sql$, $sql$Complete Balloon Garland Kit$sql$, $sql$FE-KIT-GAR$sql$, (select id from public.categories where slug = $sql$accessories$sql$), NULL, NULL, 89, 120, $json$["Rose Gold","Blue","Gold"]$json$::jsonb, $json$[{"label":"4 m kit","price":89}]$json$::jsonb, $json$[{"label":"Includes","value":"120 balloons + strip + dots + tool"},{"label":"Finished length","value":"Approx. 4 m"}]$json$::jsonb, $sql$Everything for a 4 metre garland.$sql$, $sql$One box, one garland: 120 balloons in graded sizes, decorating strip, glue dots and tying tool. The fastest route from van to venue.$sql$, $json${"kind":"cluster","color":"#e8bcae"}$json$::jsonb, $sql$Value kit$sql$, false, 4.9, 76)
on conflict (slug) do update set
  name = excluded.name, sku = excluded.sku, category_id = excluded.category_id, shape = excluded.shape,
  theme = excluded.theme, price = excluded.price, compare_at = excluded.compare_at, colors = excluded.colors,
  sizes = excluded.sizes, specs = excluded.specs, short = excluded.short, description = excluded.description,
  visual = excluded.visual, badge = excluded.badge, is_featured = excluded.is_featured,
  rating = excluded.rating, reviews_count = excluded.reviews_count, updated_at = now();

